package com.constellio.app.ui.pages.events;

public enum EventCategory {
	SYSTEM_USAGE,
	USERS_AND_GROUPS_ADD_OR_REMOVE,
	FOLDERS_AND_DOCUMENTS_CREATION,
	FOLDERS_AND_DOCUMENTS_MODIFICATION,
	FOLDERS_AND_DOCUMENTS_DELETION,
	CURRENTLY_BORROWED_DOCUMENTS,
	CURRENTLY_BORROWED_FOLDERS,
	DOCUMENTS_BORROW_OR_RETURN,
	FOLDERS_BORROW_OR_RETURN,
	CONTAINERS_BORROW_OR_RETURN,
	EVENTS_BY_ADMINISTRATIVE_UNIT,
	EVENTS_BY_FOLDER,
	EVENTS_BY_CONTAINER,
	EVENTS_BY_USER,
	CONNECTED_USERS_EVENT,
	DECOMMISSIONING_EVENTS,
	AGENT_EVENTS,
	TASKS_EVENTS,
	REINDEX_AND_RESTART,
	REQUEST_TASKS,
	IMPORT_EXPORT,
	BATCH_PROCESS_EVENTS,
	SIGNED_DOCUMENTS,
	// FIXME should be in plugin, extension/refactor needed
	CURRENTLY_EMPTY_DOCUMENTS,
	SCANNED_DOCUMENTS
}
