package com.constellio.app.services.metadata;

public enum DeletionProhibitionReason {
	POPULATED_METADATA, INHERITED_METADATA, COPIED_METADATA_SOURCE, FACET_METADATA,
	COPIED_METADATA_REFERENCE, CALCULATED_METADATA_SOURCE, EXTRACTED_METADATA_SOURCE;
}

