/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{349:function(ha,da,h){h.r(da);h.d(da,"ByteRangeRequest",function(){return la});var ca=h(3),aa=h(0);h.n(aa);var fa=h(1),ea=h(119);ha=h(75);var z=h(202),x=h(53),e=h(49),f=h(201),y=h(135);h=h(303);var r=[],n=[],w=window,ba=function(){return function(){this.Ik=1}}(),ia;(function(e){e[e.UNSENT=0]="UNSENT";e[e.DONE=4]="DONE"})(ia||(ia={}));var la=function(){function e(e,h,n,r){var y=this;this.url=e;this.range=h;this.Af=n;this.withCredentials=
r;this.SV=ia;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);w.Uint8Array&&(this.request.responseType="arraybuffer");r&&(this.request.withCredentials=r);pa.DISABLE_RANGE_HEADER||(Object(aa.isUndefined)(h.stop)?this.request.setRequestHeader("Range","bytes="+h.start):this.request.setRequestHeader("Range",["bytes=",h.start,"-",h.stop-1].join("")));this.request.setRequestHeader("X-Requested-With","XMLHttpRequest");n&&Object.keys(n).forEach(function(e){y.request.setRequestHeader(e,
n[e])});this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=f.a.NOT_STARTED}e.prototype.start=function(e){var h=this,n=this.request;n.onreadystatechange=function(){if(h.aborted)return h.status=f.a.ABORTED,e({code:f.a.ABORTED});if(this.readyState===h.SV.DONE){h.Wy();var r=0===window.document.URL.indexOf("file:///");200===n.status||206===n.status||r&&0===n.status?(r=w.hO(this),
h.xr(r,e)):(h.status=f.a.ERROR,e({code:h.status,status:h.status}))}};this.request.send(null);this.status=f.a.STARTED};e.prototype.xr=function(e,h){this.status=f.a.SUCCESS;if(h)return h(!1,e)};e.prototype.abort=function(){this.Wy();this.aborted=!0;this.request.abort()};e.prototype.Wy=function(){var f=Object(y.b)(this.url,this.range,n);-1!==f&&n.splice(f,1);if(0<r.length){f=r.shift();var h=new e(f.url,f.range,this.Af,this.withCredentials);f.request=h;n.push(f);h.start(Object(y.c)(f))}};e.prototype.extend=
function(e){var f=Object.assign({},this,e.prototype);f.constructor=e;return f};return e}(),pa=function(f){function h(e,h,n,r,w){n=f.call(this,e,n,r)||this;n.Kk={};n.Dx=h;n.url=e;n.DISABLE_RANGE_HEADER=!1;n.Yu=la;n.II=3;n.Af=w||{};return n}Object(ca.c)(h,f);h.prototype.Vs=function(f,h,n){var r=-1===f.indexOf("?")?"?":"&";switch(n){case !1:case e.a.NEVER_CACHE:f=f+r+"_="+Object(aa.uniqueId)();break;case !0:case e.a.CACHE:f=f+r+"_="+h.start+","+(Object(aa.isUndefined)(h.stop)?"":h.stop)}return f};h.prototype.vM=
function(e,f,h,n){void 0===h&&(h={});return new this.Yu(e,f,h,n)};h.prototype.H0=function(e,f,h,w,y){for(var x=0;x<r.length;x++)if(Object(aa.isEqual)(r[x].range,f)&&Object(aa.isEqual)(r[x].url,e))return r[x].ag.push(w),r[x].Rz++,null;for(x=0;x<n.length;x++)if(Object(aa.isEqual)(n[x].range,f)&&Object(aa.isEqual)(n[x].url,e))return n[x].ag.push(w),n[x].Rz++,null;h={url:e,range:f,Dx:h,ag:[w],Rz:1};if(0===r.length&&n.length<this.II)return n.push(h),h.request=this.vM(e,f,y,this.withCredentials),h;r.push(h);
return null};h.prototype.Yl=function(e,f,h){var w=this.Vs(e,f,this.Dx);(e=this.H0(w,f,this.Dx,h,this.Af))&&e.request.start(Object(y.c)(e));return function(){var e=Object(y.b)(w,f,n);if(-1!==e){var h=--n[e].Rz;0===h&&n[e].request&&n[e].request.abort()}else e=Object(y.b)(w,f,r),-1!==e&&(h=--r[e].Rz,0===h&&r.splice(e,1))}};h.prototype.LN=function(){return{start:-ea.a}};h.prototype.E3=function(){var e=-(ea.a+ea.e);return{start:e-ea.d,end:e}};h.prototype.Lq=function(e){var f=this;this.Ix=!0;var h=ea.a;
this.Yl(this.url,this.LN(),function(n,r,w){function y(){var h=f.Hd.IN();f.Yl(f.url,h,function(n,r){if(n)return Object(fa.h)("Error loading central directory: "+n),e(n);r=Object(x.a)(r);if(r.length!==h.stop-h.start)return e("Invalid XOD file: Zip central directory data is wrong size! Should be "+(h.stop-h.start)+" but is "+r.length);f.Hd.cR(r);f.kD=!0;f.Ix=!1;return e(!1)})}if(n)return Object(fa.h)("Error loading end header: "+n),e(n,r,w);r=Object(x.a)(r);if(r.length!==h)return e("Invalid XOD file: Zip end header data is wrong size!");
try{f.Hd=new z.a(r)}catch(ua){return e(ua)}f.Hd.a5?f.Yl(f.url,f.E3(),function(h,n){if(h)return Object(fa.h)("Error loading zip64 header: "+h),e(h);n=Object(x.a)(n);f.Hd.r5(n);y()}):y()})};h.prototype.eO=function(e){e(Object.keys(this.Hd.Il))};h.prototype.LG=function(e,f){var h=this;if(this.Hd.nM(e)){var n=this.Hd.Py(e);if(n in this.Kk){var r=this.Wg[e];r.Mp=this.Kk[n];r.Mp.Ik++;r.cancel=r.Mp.cancel}else{var w=this.Hd.Z1(e),y=this.Yl(this.url,w,function(r,y){r?(Object(fa.h)('Error loading part "'+
e+'": '+r),h.Yl(h.url,w,function(r,y){if(r)return f(r,e);h.gR(y,w,n,e,f)})):h.gR(y,w,n,e,f)}),x=this.Wg[e];x&&(x.lT=!0,x.cancel=function(){x.Mp.Ik--;0===x.Mp.Ik&&(y(),delete h.Kk[n])},this.Kk[n]=new ba(n),x.Mp=this.Kk[n],x.Mp.cancel=x.cancel)}}else delete this.Wg[e],f(Error('File not found: "'+e+'"'),e)};h.prototype.gR=function(e,f,h,n,r){if(e.length!==f.stop-f.start)r(Error("Part data is wrong size!"),n);else{do{if(!this.Kk[h])return;n=this.Kk[h].Ik;for(var w=f.Eo.length,y=0;y<w;++y){var x=f.Eo[y];
r(!1,x.zo,e["string"===typeof e?"substring":"subarray"](x.start,x.stop),this.Hd.gP(x.zo));x.zo in this.Wg&&delete this.Wg[x.zo]}}while(n!==this.Kk[h].Ik);delete this.Kk[h]}};h.DISABLE_RANGE_HEADER=!1;h.II=3;return h}(ha.a);(function(e){function f(f,h,n){var r=e.call(this)||this,w;for(w in f)r[w]=f[w];r.Iea=f;r.startOffset=h;r.endOffset=n;r.vM=function(e,h,n,w){Object(aa.isUndefined)(h.stop)?(h.start+=r.endOffset,h.stop=r.endOffset):(h.start+=r.startOffset,h.stop+=r.startOffset);e=r.Vs(r.url,h,r.Dx);
return new f.Yu(e,h,n,w)};return r}Object(ca.c)(f,e);return f})(pa);Object(h.a)(pa);Object(h.b)(pa);da["default"]=pa}}]);}).call(this || window)
