package com.constellio.app.modules.rm.services.menu;

public enum MenuItemActionType {
	DOCUMENT_DISPLAY, DOCUMENT_OPEN, DOCUMENT_EDIT, DOCUMENT_DOWNLOAD, DOCUMENT_DELETE, DOCUMENT_COPY, DOCUMENT_MOVE, DOCUMENT_FINALIZE,
	DOCUMENT_PUBLISH, DOCUMENT_CREATE_PDF, DOCUMENT_ADD_TO_SELECTION, DOCUMENT_REMOVE_TO_SELECTION, DOCUMENT_ADD_TO_CART, DOCUMENT_ADD_TO_MY_CART,
	DOCUMENT_UPLOAD,
	//
	//
	//
	FOLDER_ADD_DOCUMENT, FOLDER_MOVE, FOLDER_ADD_SUBFOLDER, FOLDER_DISPLAY, FOLDER_EDIT, FOLDER_DELETE;
}
