package com.constellio.app.modules.rm.services.menu;

public enum MenuItemActionType {
	DOCUMENT_DISPLAY, DOCUMENT_OPEN, DOCUMENT_EDIT, DOCUMENT_DOWNLOAD, DOCUMENT_DELETE, DOCUMENT_COPY, DOCUMENT_MOVE,
	//
	//
	//
	FOLDER_ADD_DOCUMENT, FOLDER_MOVE, FOLDER_ADD_SUBFOLDER, FOLDER_DISPLAY, FOLDER_EDIT, FOLDER_DELETE;
}
